name: Auto FFmpeg Processor

on:
  push:
    paths:
      - 'media/Test.MP4'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Git Configuration
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Process Video with FFmpeg
      run: |
        cd media
        rm -f Test1.MP4
        # ใช้คำสั่งเดิมของคุณ (-codec copy จะไม่บีบอัดภาพและคงความละเอียดเดิม 100%)
        ffmpeg -itsscale 2 -i Test.MP4 -codec copy Test1.MP4

    # 📥 เพิ่มขั้นตอนนี้เข้าไปเพื่ออัปโหลดไฟล์ดิบเก็บไว้บน GitHub Cloud แบบไม่มีการบีบอัด
    - name: Upload Uncompressed Video
      uses: actions/upload-artifact@v4
      with:
        name: Original-1080p-Video # ชื่อแพ็กเกจไฟล์
        path: media/Test1.MP4       # พาธไฟล์ที่ต้องการเก็บ
